// data/flightsData.js
const flightsData = [
  // Indian Cities
  {
    id: 1,
    city: "Delhi",
    country: "India",
    airport: "Indira Gandhi International Airport",
    airportCode: "DEL",
    price: 4500,
    duration: "2h 30m",
    airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "Go First"],
    fromIndia: false,
    distance: "0 km",
    image:
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=400",
  },
  {
    id: 2,
    city: "Mumbai",
    country: "India",
    airport: "Chhatrapati Shivaji Maharaj International Airport",
    airportCode: "BOM",
    price: 5200,
    duration: "2h 10m",
    airlines: ["IndiGo", "Air India", "Vistara", "Akasa Air", "SpiceJet"],
    fromIndia: false,
    distance: "1,410 km",
    image:
      "https://images.unsplash.com/photo-1529254479751-fbacb4c9a550?auto=format&fit=crop&w=400",
  },
  {
    id: 3,
    city: "Bangalore",
    country: "India",
    airport: "Kempegowda International Airport",
    airportCode: "BLR",
    price: 4800,
    duration: "2h 45m",
    airlines: ["IndiGo", "Air India", "Akasa Air", "SpiceJet", "AirAsia India"],
    fromIndia: false,
    distance: "1,750 km",
    image:
      "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=400",
  },
  {
    id: 4,
    city: "Hyderabad",
    country: "India",
    airport: "Rajiv Gandhi International Airport",
    airportCode: "HYD",
    price: 4200,
    duration: "2h 15m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "TruJet"],
    fromIndia: false,
    distance: "1,260 km",
    image:
      "https://images.unsplash.com/photo-1595599512946-425d0f7f3b19?auto=format&fit=crop&w=400",
  },
  {
    id: 5,
    city: "Chennai",
    country: "India",
    airport: "Chennai International Airport",
    airportCode: "MAA",
    price: 4600,
    duration: "2h 50m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Air India Express"],
    fromIndia: false,
    distance: "1,760 km",
    image:
      "https://images.unsplash.com/photo-1565967511849-76a60a516170?auto=format&fit=crop&w=400",
  },
  {
    id: 6,
    city: "Kolkata",
    country: "India",
    airport: "Netaji Subhash Chandra Bose International Airport",
    airportCode: "CCU",
    price: 5100,
    duration: "2h 25m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Go First"],
    fromIndia: false,
    distance: "1,305 km",
    image:
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=400",
  },
  {
    id: 7,
    city: "Goa",
    country: "India",
    airport: "Goa International Airport",
    airportCode: "GOI",
    price: 6800,
    duration: "2h 30m",
    airlines: ["IndiGo", "Air India", "Vistara", "SpiceJet", "Go First"],
    fromIndia: false,
    distance: "1,535 km",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=400",
  },
  {
    id: 8,
    city: "Pune",
    country: "India",
    airport: "Pune Airport",
    airportCode: "PNQ",
    price: 4400,
    duration: "2h 00m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa Air"],
    fromIndia: false,
    distance: "1,175 km",
    image:
      "https://images.unsplash.com/photo-1562979314-bee7453e911c?auto=format&fit=crop&w=400",
  },

  // International Destinations
  {
    id: 9,
    city: "Dubai",
    country: "UAE",
    airport: "Dubai International Airport",
    airportCode: "DXB",
    price: 18500,
    duration: "3h 30m",
    airlines: ["Emirates", "Air India", "IndiGo", "flydubai", "SpiceJet"],
    fromIndia: true,
    distance: "1,945 km",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=400",
  },
  {
    id: 10,
    city: "Singapore",
    country: "Singapore",
    airport: "Changi Airport",
    airportCode: "SIN",
    price: 22500,
    duration: "5h 45m",
    airlines: ["Singapore Airlines", "Air India", "IndiGo", "Scoot", "Vistara"],
    fromIndia: true,
    distance: "3,915 km",
    image:
      "https://images.unsplash.com/photo-1530569673472-307dc017a82d?auto=format&fit=crop&w=400",
  },
  {
    id: 11,
    city: "Bangkok",
    country: "Thailand",
    airport: "Suvarnabhumi Airport",
    airportCode: "BKK",
    price: 16500,
    duration: "3h 50m",
    airlines: [
      "Thai Airways",
      "Air India",
      "IndiGo",
      "Bangkok Airways",
      "SpiceJet",
    ],
    fromIndia: true,
    distance: "2,575 km",
    image:
      "https://images.unsplash.com/photo-1558769132-cb89483fda8e?auto=format&fit=crop&w=400",
  },
  {
    id: 12,
    city: "London",
    country: "UK",
    airport: "Heathrow Airport",
    airportCode: "LHR",
    price: 48500,
    duration: "9h 30m",
    airlines: ["British Airways", "Air India", "Virgin Atlantic", "Vistara"],
    fromIndia: true,
    distance: "6,715 km",
    image:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=400",
  },
  {
    id: 13,
    city: "New York",
    country: "USA",
    airport: "John F. Kennedy International Airport",
    airportCode: "JFK",
    price: 68500,
    duration: "15h 20m",
    airlines: ["Air India", "United Airlines", "Delta", "American Airlines"],
    fromIndia: true,
    distance: "11,625 km",
    image:
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=400",
  },
  {
    id: 14,
    city: "Paris",
    country: "France",
    airport: "Charles de Gaulle Airport",
    airportCode: "CDG",
    price: 42500,
    duration: "8h 45m",
    airlines: ["Air France", "Air India", "IndiGo", "Vistara"],
    fromIndia: true,
    distance: "6,590 km",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=400",
  },
  {
    id: 15,
    city: "Tokyo",
    country: "Japan",
    airport: "Narita International Airport",
    airportCode: "NRT",
    price: 38500,
    duration: "8h 10m",
    airlines: ["Japan Airlines", "Air India", "ANA", "IndiGo"],
    fromIndia: true,
    distance: "5,860 km",
    image:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=400",
  },
  {
    id: 16,
    city: "Sydney",
    country: "Australia",
    airport: "Sydney Airport",
    airportCode: "SYD",
    price: 52500,
    duration: "12h 45m",
    airlines: ["Qantas", "Air India", "Singapore Airlines"],
    fromIndia: true,
    distance: "9,340 km",
    image:
      "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=400",
  },
  {
    id: 17,
    city: "Colombo",
    country: "Sri Lanka",
    airport: "Bandaranaike International Airport",
    airportCode: "CMB",
    price: 12500,
    duration: "1h 45m",
    airlines: ["SriLankan Airlines", "Air India", "IndiGo", "SpiceJet"],
    fromIndia: true,
    distance: "1,045 km",
    image:
      "https://images.unsplash.com/photo-1556155097-4fd6a7e73a7e?auto=format&fit=crop&w=400",
  },
  {
    id: 18,
    city: "Kathmandu",
    country: "Nepal",
    airport: "Tribhuvan International Airport",
    airportCode: "KTM",
    price: 9500,
    duration: "1h 30m",
    airlines: ["Nepal Airlines", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "850 km",
    image:
      "https://images.unsplash.com/photo-1553949284-bdcb31e6f9fe?auto=format&fit=crop&w=400",
  },
  {
    id: 19,
    city: "Male",
    country: "Maldives",
    airport: "Velana International Airport",
    airportCode: "MLE",
    price: 21500,
    duration: "2h 30m",
    airlines: ["Maldivian", "Air India", "IndiGo", "SpiceJet"],
    fromIndia: true,
    distance: "1,325 km",
    image:
      "https://images.unsplash.com/photo-1590523541548-7c56d6c2d4e4?auto=format&fit=crop&w=400",
  },
  {
    id: 20,
    city: "Dhaka",
    country: "Bangladesh",
    airport: "Hazrat Shahjalal International Airport",
    airportCode: "DAC",
    price: 11500,
    duration: "2h 00m",
    airlines: ["Biman Bangladesh Airlines", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "1,415 km",
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=400",
  },

  // More International Destinations
  {
    id: 21,
    city: "Hong Kong",
    country: "China",
    airport: "Hong Kong International Airport",
    airportCode: "HKG",
    price: 28500,
    duration: "5h 15m",
    airlines: ["Cathay Pacific", "Air India", "IndiGo", "Vistara"],
    fromIndia: true,
    distance: "3,840 km",
    image:
      "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=400",
  },
  {
    id: 22,
    city: "Frankfurt",
    country: "Germany",
    airport: "Frankfurt Airport",
    airportCode: "FRA",
    price: 39500,
    duration: "8h 20m",
    airlines: ["Lufthansa", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "6,325 km",
    image:
      "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?auto=format&fit=crop&w=400",
  },
  {
    id: 23,
    city: "Amsterdam",
    country: "Netherlands",
    airport: "Schiphol Airport",
    airportCode: "AMS",
    price: 40500,
    duration: "8h 45m",
    airlines: ["KLM", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "6,450 km",
    image:
      "https://images.unsplash.com/photo-1512470886500-3c09c85c1663?auto=format&fit=crop&w=400",
  },
  {
    id: 24,
    city: "Istanbul",
    country: "Turkey",
    airport: "Istanbul Airport",
    airportCode: "IST",
    price: 28500,
    duration: "6h 15m",
    airlines: ["Turkish Airlines", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "4,635 km",
    image:
      "https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=400",
  },
  {
    id: 25,
    city: "Beijing",
    country: "China",
    airport: "Beijing Capital International Airport",
    airportCode: "PEK",
    price: 32500,
    duration: "6h 45m",
    airlines: ["Air China", "Air India", "China Eastern"],
    fromIndia: true,
    distance: "3,785 km",
    image:
      "https://images.unsplash.com/photo-1547981609-4b6bf67b7d46?auto=format&fit=crop&w=400",
  },
  {
    id: 26,
    city: "Seoul",
    country: "South Korea",
    airport: "Incheon International Airport",
    airportCode: "ICN",
    price: 29500,
    duration: "6h 30m",
    airlines: ["Korean Air", "Air India", "Asiana Airlines"],
    fromIndia: true,
    distance: "4,250 km",
    image:
      "https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?auto=format&fit=crop&w=400",
  },
  {
    id: 27,
    city: "Kuala Lumpur",
    country: "Malaysia",
    airport: "Kuala Lumpur International Airport",
    airportCode: "KUL",
    price: 18500,
    duration: "4h 15m",
    airlines: ["Malaysia Airlines", "Air India", "IndiGo", "AirAsia"],
    fromIndia: true,
    distance: "3,125 km",
    image:
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f11?auto=format&fit=crop&w=400",
  },
  {
    id: 28,
    city: "Muscat",
    country: "Oman",
    airport: "Muscat International Airport",
    airportCode: "MCT",
    price: 14500,
    duration: "3h 00m",
    airlines: ["Oman Air", "Air India", "IndiGo", "SalamAir"],
    fromIndia: true,
    distance: "1,675 km",
    image:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=400",
  },
  {
    id: 29,
    city: "Doha",
    country: "Qatar",
    airport: "Hamad International Airport",
    airportCode: "DOH",
    price: 17500,
    duration: "3h 30m",
    airlines: ["Qatar Airways", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "1,935 km",
    image:
      "https://images.unsplash.com/photo-1544525977-854b5c4b2e64?auto=format&fit=crop&w=400",
  },
  {
    id: 30,
    city: "Riyadh",
    country: "Saudi Arabia",
    airport: "King Khalid International Airport",
    airportCode: "RUH",
    price: 19500,
    duration: "4h 15m",
    airlines: ["Saudia", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "2,450 km",
    image:
      "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?auto=format&fit=crop&w=400",
  },

  // More Indian Cities
  {
    id: 31,
    city: "Ahmedabad",
    country: "India",
    airport: "Sardar Vallabhbhai Patel International Airport",
    airportCode: "AMD",
    price: 4200,
    duration: "1h 45m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa Air"],
    fromIndia: false,
    distance: "785 km",
    image:
      "https://images.unsplash.com/photo-1564501049418-3c27787d01e8?auto=format&fit=crop&w=400",
  },
  {
    id: 32,
    city: "Lucknow",
    country: "India",
    airport: "Chaudhary Charan Singh International Airport",
    airportCode: "LKO",
    price: 3800,
    duration: "1h 15m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Akasa Air"],
    fromIndia: false,
    distance: "420 km",
    image:
      "https://images.unsplash.com/photo-1564501049418-3c27787d01e8?auto=format&fit=crop&w=400",
  },
  {
    id: 33,
    city: "Jaipur",
    country: "India",
    airport: "Jaipur International Airport",
    airportCode: "JAI",
    price: 3500,
    duration: "1h 00m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"],
    fromIndia: false,
    distance: "240 km",
    image:
      "https://images.unsplash.com/photo-1593693399744-3d0c4c6c1de6?auto=format&fit=crop&w=400",
  },
  {
    id: 34,
    city: "Chandigarh",
    country: "India",
    airport: "Chandigarh International Airport",
    airportCode: "IXC",
    price: 3200,
    duration: "0h 50m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "Vistara"],
    fromIndia: false,
    distance: "205 km",
    image:
      "https://images.unsplash.com/photo-1586769852044-692a501d9a5c?auto=format&fit=crop&w=400",
  },
  {
    id: 35,
    city: "Guwahati",
    country: "India",
    airport: "Lokpriya Gopinath Bordoloi International Airport",
    airportCode: "GAU",
    price: 6800,
    duration: "2h 45m",
    airlines: ["IndiGo", "Air India", "SpiceJet"],
    fromIndia: false,
    distance: "1,485 km",
    image:
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=400",
  },
  {
    id: 36,
    city: "Kochi",
    country: "India",
    airport: "Cochin International Airport",
    airportCode: "COK",
    price: 7500,
    duration: "3h 15m",
    airlines: ["IndiGo", "Air India", "SpiceJet", "AirAsia India"],
    fromIndia: false,
    distance: "2,045 km",
    image:
      "https://images.unsplash.com/photo-1553272725-086100b1facc?auto=format&fit=crop&w=400",
  },
  {
    id: 37,
    city: "Thiruvananthapuram",
    country: "India",
    airport: "Trivandrum International Airport",
    airportCode: "TRV",
    price: 8200,
    duration: "3h 30m",
    airlines: ["IndiGo", "Air India", "SpiceJet"],
    fromIndia: false,
    distance: "2,185 km",
    image:
      "https://images.unsplash.com/photo-1558383409-ab7ef8db3e01?auto=format&fit=crop&w=400",
  },
  {
    id: 38,
    city: "Varanasi",
    country: "India",
    airport: "Lal Bahadur Shastri International Airport",
    airportCode: "VNS",
    price: 4100,
    duration: "1h 30m",
    airlines: ["IndiGo", "Air India", "SpiceJet"],
    fromIndia: false,
    distance: "585 km",
    image:
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=400",
  },
  {
    id: 39,
    city: "Nagpur",
    country: "India",
    airport: "Dr. Babasaheb Ambedkar International Airport",
    airportCode: "NAG",
    price: 5200,
    duration: "1h 45m",
    airlines: ["IndiGo", "Air India", "SpiceJet"],
    fromIndia: false,
    distance: "765 km",
    image:
      "https://images.unsplash.com/photo-1586769852044-692a501d9a5c?auto=format&fit=crop&w=400",
  },
  {
    id: 40,
    city: "Visakhapatnam",
    country: "India",
    airport: "Visakhapatnam Airport",
    airportCode: "VTZ",
    price: 5800,
    duration: "2h 15m",
    airlines: ["IndiGo", "Air India", "SpiceJet"],
    fromIndia: false,
    distance: "1,150 km",
    image:
      "https://images.unsplash.com/photo-1558383409-ab7ef8db3e01?auto=format&fit=crop&w=400",
  },

  // More Countries
  {
    id: 41,
    city: "Zurich",
    country: "Switzerland",
    airport: "Zurich Airport",
    airportCode: "ZRH",
    price: 44500,
    duration: "8h 00m",
    airlines: ["Swiss International Air Lines", "Air India", "Lufthansa"],
    fromIndia: true,
    distance: "6,125 km",
    image:
      "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=400",
  },
  {
    id: 42,
    city: "Rome",
    country: "Italy",
    airport: "Leonardo da Vinci–Fiumicino Airport",
    airportCode: "FCO",
    price: 39500,
    duration: "8h 30m",
    airlines: ["Alitalia", "Air India", "IndiGo"],
    fromIndia: true,
    distance: "5,985 km",
    image:
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=400",
  },
  {
    id: 43,
    city: "Madrid",
    country: "Spain",
    airport: "Adolfo Suárez Madrid–Barajas Airport",
    airportCode: "MAD",
    price: 41500,
    duration: "9h 15m",
    airlines: ["Iberia", "Air India", "British Airways"],
    fromIndia: true,
    distance: "6,785 km",
    image:
      "https://images.unsplash.com/photo-1543785734-4b6e564642f8?auto=format&fit=crop&w=400",
  },
  {
    id: 44,
    city: "Vienna",
    country: "Austria",
    airport: "Vienna International Airport",
    airportCode: "VIE",
    price: 38500,
    duration: "7h 45m",
    airlines: ["Austrian Airlines", "Air India", "Lufthansa"],
    fromIndia: true,
    distance: "5,645 km",
    image:
      "https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=400",
  },
  {
    id: 45,
    city: "Stockholm",
    country: "Sweden",
    airport: "Stockholm Arlanda Airport",
    airportCode: "ARN",
    price: 46500,
    duration: "9h 00m",
    airlines: ["SAS", "Air India", "Finnair"],
    fromIndia: true,
    distance: "5,985 km",
    image:
      "https://images.unsplash.com/photo-1513941024782-50f5b64d2e15?auto=format&fit=crop&w=400",
  },
  {
    id: 46,
    city: "Helsinki",
    country: "Finland",
    airport: "Helsinki Airport",
    airportCode: "HEL",
    price: 47500,
    duration: "9h 30m",
    airlines: ["Finnair", "Air India"],
    fromIndia: true,
    distance: "5,450 km",
    image:
      "https://images.unsplash.com/photo-1508138221679-760a23a2285b?auto=format&fit=crop&w=400",
  },
  {
    id: 47,
    city: "Copenhagen",
    country: "Denmark",
    airport: "Copenhagen Airport",
    airportCode: "CPH",
    price: 42500,
    duration: "8h 45m",
    airlines: ["SAS", "Air India", "Lufthansa"],
    fromIndia: true,
    distance: "5,785 km",
    image:
      "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&w=400",
  },
  {
    id: 48,
    city: "Oslo",
    country: "Norway",
    airport: "Oslo Airport",
    airportCode: "OSL",
    price: 48500,
    duration: "9h 15m",
    airlines: ["Norwegian", "Air India", "SAS"],
    fromIndia: true,
    distance: "5,645 km",
    image:
      "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=400",
  },
  {
    id: 49,
    city: "Dublin",
    country: "Ireland",
    airport: "Dublin Airport",
    airportCode: "DUB",
    price: 45500,
    duration: "10h 00m",
    airlines: ["Aer Lingus", "Air India", "British Airways"],
    fromIndia: true,
    distance: "6,985 km",
    image:
      "https://images.unsplash.com/photo-1549918864-480f5b8d04aa?auto=format&fit=crop&w=400",
  },
  {
    id: 50,
    city: "Brussels",
    country: "Belgium",
    airport: "Brussels Airport",
    airportCode: "BRU",
    price: 40500,
    duration: "8h 30m",
    airlines: ["Brussels Airlines", "Air India", "Lufthansa"],
    fromIndia: true,
    distance: "6,250 km",
    image:
      "https://images.unsplash.com/photo-1511735111819-9a3f7709049c?auto=format&fit=crop&w=400",
  },
];

export default flightsData;
